version: '3'
services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  streamlit-app:
    image: tyulpin/private-chat-with-multipdfs:0.1
    build: ./app
    command: streamlit run cmd/app.py --server.port 8501
    volumes:
      - ./cmd/:/app/cmd
    ports:
      - 8501:8501